spring:
  application:
    name: back
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}.postgres.database.azure.com:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASS}
  mail:
    host: smtp.naver.com
    port: 587
    username: ${MAILUSER}
    password: ${MAILPASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false

logging:
  level:
    root: DEBUG

jwt:
  secret: ${JWT_SECRET}

admin:
  id: ${ADMIN_ID}
  password: ${ADMIN_PASS}

ai:
  protocols: ${AI_PROTOCOLS}
chatai:
  host: ${CHATAI_HOST}
  port: ${CHATAI_PORT}