spring:
  application:
    name: back
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://aivle-bigp-18-db.postgres.database.azure.com:5432/postgres?serverTimezone=Asia/Seoul
    username: aivlePostgres
    password: ssss1185!
  mail:
    host: smtp.naver.com
    port: 587
    username: wnwoduq@naver.com
    password: dhrtus56
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
jwt:
  secret: wefewfewfwefqwdqwdqwfwef

admin:
  id: wnwoduq@naver.com
  password: string@123

ai:
  protocols: http
chatai:
  host: chatai
  port: 8001